### PR TITLE
fix: Upgrade to cobalt#346

### PR DESCRIPTION
**Pull request by epage**
*DO NOT MERGE THIS YET* The PR is not yet merged or released.  I'm posting PRs for all known cobalt blogs.  After that, I'll try to give a feedback window before merging the PR and creating a release.

Feedback on https://github.com/cobalt-org/cobalt.rs/pull/346 is welcome.  In addition to this PR, you can peruse the updated [documentation](https://cobalt-org.github.io/).

Commands run
- `cobalt migrate`
- `rm _includes/default.liquid`
- `rm _layouts/_*.liquid`
- Manually fixed `{% assign post_count = posts | size %}`

Includes https://github.com/booyaa/booyaa.github.io/pull/3

### CODE REVIEW

**Comment by booyaa** [comment]
thanks for both the PRs!

sorry it's taken me so long to get back, looks good. is there an easy way to install this version of cobalt?

I'm currently on v0.10.0

**Comment by booyaa** [comment]
I might have worked it out: `cargo install -f --git https://github.com/epage/cobalt.rs --branch "feat/migrate" cobalt-bin`

**Comment by epage** [comment]
Yeah, now that all of the PRs have been created, I'm probably going to merge to master soon which will be one step towards making it easier to play around with.  I'll then give it a couple more days before making a release (depending on the level of feedback).

**Comment by epage** [comment]
v0.11 is now released

**Pull request merged**
